### ISSUE TITLE
When scrolling through the results, the audio equalizer pauses

### ISSUE THREAD

**Issue by iTarek** [alfianlosari/ChatGPTUI#3]
https://github.com/alfianlosari/ChatGPTUI/assets/693715/8bfeabe7-3f2e-4721-b8f8-167c882349c1

Is there any way to make the audio equalizer not affected by the scroll?

**Comment by alfianlosari** [comment]
Hi, i've fixed this bug in version 0.2.6 https://github.com/alfianlosari/ChatGPTUI/releases/tag/0.2.6
Simply update the package, thanks for reporting!


https://github.com/alfianlosari/ChatGPTUI/assets/6789991/9213471f-7049-462b-bccd-2ceebf0ea3fb

**Comment by iTarek** [comment]
Can you explain how you fixed it?
